/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.github.johnflanigan.dnasequencetool.api;

import io.github.johnflanigan.dnasequencetool.model.Sequences;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Api(value = "sequences", description = "the sequences API")
public interface SequencesApi {

	@ApiOperation(value = "Create a sequence", nickname = "createSequences", notes = "", tags = {"sequences",})
	@ApiResponses(value = {
			@ApiResponse(code = 201, message = "Null response"),
			@ApiResponse(code = 200, message = "unexpected error", response = Error.class)})
	@RequestMapping(value = "/sequences",
			produces = {"application/json"},
			method = RequestMethod.POST)
	ResponseEntity<Void> createSequences();

	@ApiOperation(value = "List all sequences", nickname = "listSequences", notes = "", response = Sequences.class, tags = {"sequences",})
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "An array of sequences", response = Sequences.class),
			@ApiResponse(code = 200, message = "unexpected error", response = Error.class)})
	@RequestMapping(value = "/sequences",
			produces = {"application/json"},
			method = RequestMethod.GET)
	ResponseEntity<Sequences> listSequences();

}

